services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ab_user
      POSTGRES_PASSWORD: 1q2w3e
      POSTGRES_DB: ab_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/dump:ro
      - ./scripts:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ab_user -d ab_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: